### ISSUE TITLE
Questions about the codes and pre-trained models

### ISSUE THREAD

**Issue by 13952522076** [tiangexiang/CurveNet#1]
Hi Tiange, 

Congrats on your paper been accepted by ICCV2021, and thanks a lot for your great work!

I have read CurveNet, and tried to implement it. However, due to limited computational resources and my lack of experience, could you please share your codes and the pre-trained models as you indicated previously (say, 93.8/94.2 for ModelNet40 and 86.6/86.8 for ShapeNet)? The log files are also welcome.  This will help our research a lot.

Thanks,
Xu

**Comment by tiangexiang** [comment]
Hi Xu, thanks for your interest! We are now doing the final cleaning, and all codes/pre-trained models will be released no later than mid-August. Please stay stunned!

**Comment by 13952522076** [comment]
> Hi Xu, thanks for your interest! We are now doing the final cleaning, and all codes/pre-trained models will be released no later than mid-August. Please stay stunned!

@tiangexiang Thanks a lot!

**Comment by tiangexiang** [comment]
Hi, our source codes and pretrained models/logs have been released. Please refer to README.md for details. Thanks!

**Comment by 13952522076** [comment]
> Hi, our source codes and pretrained models/logs have been released. Please refer to README.md for details. Thanks!

@tiangexiang Thanks a lot for your kind remind.
