### ISSUE TITLE
could not reproduce classification results

### ISSUE THREAD

**Issue by rabbiahassan** [tiangexiang/CurveNet#10]
Hello !
Your work is very interesting.Thanks for sharing.
I trained and tested the classification network as per the instructions given by you on github page but results are far from what you have posted in the paper.
I would really ppriciate if you can comment on it.
![image](https://user-images.githubusercontent.com/52703791/136885525-fa7476f0-b1d3-49d2-b892-8f0a3dbe903b.png)

**Comment by tiangexiang** [comment]
Hi, 0.927 classification accuracy is really strange, the plain backbone (even DGCNN) performs much better than this. Can you please post your training log? That will help identify the problem. Thanks!
