### ISSUE TITLE
How to set radius and num_points for custom dataset?

### ISSUE THREAD

**Issue by mikkelmedm** [tiangexiang/CurveNet#22]
Many thanks for your amazing project!

As the title says, I am working on a custom dataset, currently training on 1 GPU only. As such, every iteration is very slow, and was hoping you could help guide me about the intuition of setting the parameters of the model?
Do num_points need to be the same as the amount of points in your point cloud?
Is radius dependent on your dataset? 

I am trying to predict angles and translations of planes intersecting my pointclouds, so it's essentially a regression task of a rotation and a translation matrix, with my pointcloud being centered and unit scaled.
Hope you can help me :)

**Comment by harryseely** [comment]
Hi @mikkelmedm! I am not sure about altering the radius, but I can tell you how I fixed the number of points issue to make the network work with more than 1024 points (e.g.,  2048, 3072, 4096, 5120, etc....).

When the curvnet class is described, you can add another argument for num points (see below). This can then be fed into the first CIC layer in the npoint argument (shown below). The remaining CIC layer npoint arguments do not need to be modified. 


class CurveNet(nn.Module):
    def __init__(self, num_points, k=20, setting='default'):
        super(CurveNet, self).__init__()

        assert setting in curve_config

        self.num_points = num_points

       additional_channel = 32
        self.lpfa = LPFA(9, additional_channel, k=k, mlp_num=1, initial=True)

        # encoder
        self.cic11 = CIC(npoint=self.num_points, radius=0.05, k=k, in_channels=additional_channel, output_channels=64,
                         bottleneck_ratio=2, mlp_num=1, curve_config=curve_config[setting][0])


Hope this helps!
