### ISSUE TITLE
Can this model be transformed to ONNX file?

### ISSUE THREAD

**Issue by Ying-Jieh** [tiangexiang/CurveNet#7]
How to transform the .pth or .t7 file to ONNX file?
Thanks.

**Comment by tiangexiang** [comment]
Hi, sorry that I haven't had any experiences on ONNX before, maybe you can have a look at this guide: https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

**Comment by Ying-Jieh** [comment]
I got it. Thank you!

**Comment by tiangexiang** [comment]
Closing for now, feal free to reopen if the issue still exists :)
