### ISSUE TITLE
classification normal?

### ISSUE THREAD

**Issue by swzaaaaaaa** [tiangexiang/CurveNet#9]
nohup: ignoring input
Namespace(batch_size=32, epochs=200, eval=False, exp_name='exp', lr=0.0005, model_path='', momentum=0.9, multiplier=2.0, no_cuda=False, num_points=1024, scheduler='cos', test_batch_size=16, use_sgd=True)
random seed is: 8053
Using GPU : 0 from 1 devices
Traceback (most recent call last):
  File "main_normal.py", line 208, in <module>
    train(args, io)
  File "main_normal.py", line 54, in train
    model = CurveNet(args.multiplier).to(device)
  File "/opt/data/private/swz/CurveNet-main/core/models/curvenet_normal.py", line 58, in __init__
    self.conv1 = nn.Conv1d(channels[0], num_classes, 1)
  File "/root/anaconda3/envs/pytorch_hr3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 250, in __init__
    super(Conv1d, self).__init__(
  File "/root/anaconda3/envs/pytorch_hr3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 106, in __init__
    self.weight = Parameter(torch.Tensor(
TypeError: new() received an invalid combination of arguments - got (float, int, int), but expected one of:
 * (*, torch.device device)
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
      didn't match because some of the arguments have invalid types: (!float!, !int!, !int!)
 * (object data, *, torch.device device)
      didn't match because some of the arguments have invalid types: (!float!, !int!, !int!)

**Comment by tiangexiang** [comment]
Hi, the error means the channel number specified for conv1 is a float value rather than an int value. 

At [here](https://github.com/tiangexiang/CurveNet/blob/main/core/models/curvenet_normal.py#L25), it clearly defines the channel numbers are int values. And the current code runs perfectly in my machine.

Please make sure the channel number passed to conv1 is indeed an int value :)

**Comment by swzaaaaaaa** [comment]
![image](https://user-images.githubusercontent.com/43643616/134902495-fc12680c-516f-4c8d-8d0f-bf259b4c7894.png)
不知道为啥，我这不行！

**Comment by tiangexiang** [comment]
Did you make any changes to the original code?
Also, it could be a pytorch version issue. My pytorch version is 1.4.0, can you try to adjust yours to align with mine?

**Comment by swzaaaaaaa** [comment]
我应该运行错了，分类的法向量 运行 还是main_cls吗？

**Comment by swzaaaaaaa** [comment]
Sorry, I was wrong. I thought there was a normal vector version of the classification.

**Comment by tiangexiang** [comment]
Oh ok, our classification uses XYZ coordinates only. The normals are only for the normal estimation task. Glad the problem has been solved :))

**Comment by swzaaaaaaa** [comment]
Ok, thanks for the answer.

**Comment by Summerxu86** [comment]
@swzaaaaaaa 您好，我碰到了和您一样的问题，请问最后是如何解决的呢？
